trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: dotnet restore DevOpsProject/DevOpsProject.sln
  displayName: Restore dependencies

- script: dotnet build DevOpsProject/DevOpsProject.sln --configuration $(buildConfiguration)
  displayName: Build solution

- script: dotnet test DevOpsProject/DevOpsProject.sln --configuration $(buildConfiguration)
  displayName: Run tests

- task: DotNetCoreCLI@2
  displayName: Publish app
  inputs:
    command: publish
    publishWebProjects: false
    projects: DevOpsProject/DevOpsProject.csproj
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: Deploy to Azure App Service
  inputs:
    azureSubscription: 'azure-devops-appservice-connection'
    appType: webAppLinux
    appName: devops-app-mhandzel
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
